trigger:
- main

pool: Ubuntu

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.9.x'
      displayName: 'Install Node.js'

    - script: |
        cd ./react-g2
        npm install
        npm run build
      displayName: 'npm install, build, and test'
    - task: CopyFiles@2
      displayName: 'Copy files'
      inputs:
        sourceFolder: '$(directory)/build' 
        Contents: '**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        cleanTargetFolder: true
    
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs: 
        pathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip