# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
 uiSource: '/src'
 uiBuild: '$(uiSource)/build'

pool:
  vmImage: debian-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.9'
  displayName: 'Install Node.js'

- script: |
    pushd $(uiSources)
    cd ./react-g2

    npm install
    npm run build
    popd
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(uiBuild)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true