trigger:
- main

pool: Ubuntu

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.9.x'
      displayName: 'Install Node.js'

    - script: |
        cd ./react-g2
        npm install
        npm run build
      displayName: 'npm install, build, and test'
    - task: CopyFiles@2
      displayName: 'Copy files'
      inputs:
        sourceFolder: '$(directory)/build' 
        Contents: '**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        cleanTargetFolder: true
    
- stage: deploy
  script:
    - 'cp -r ./build/ /var/www/html'