import React from 'react';
import logoImage from '../assets/montain.png';
import logoProfile from '../assets/profile-user.png';

const Navbar = () => {
  return (
    <nav className="navbar">
      <div className="navbar-container">
        <div className="navbar-logo">
          <a href="/"><img src={logoImage} alt="logo" className="logo-image" /></a>
        </div>
        <ul className="navbar-menu">
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< develop
          <li className="navbar-item">
            <a href="/profile" className='profile'><img src={logoProfile} alt="logo" className="logo-profile" /></a>
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
          <li className="navbar-item">My profile
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Dev-LG1
          </li>
        </ul>
      </div>
    </nav>
  );
};

export default Navbar;
